language: csharp  
sudo: required  
dist: trusty  
dotnet: 1.0.0-preview2-003131
env:  
  - DOTNETCORE=1
mono:  
  - none
os:  
  - linux
  - osx
osx_image: xcode7.3  
branches:  
  only:
    - master
script:  
  - dotnet restore
  - dotnet build
